name: todofrontend
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.5
  flutter_riverpod: ^3.0.0
  ferry: ^0.16.0+1
  ferry_flutter: ^0.9.1-dev.1
  graphql_flutter: ^5.2.1
  ferry_generator: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ">=2.4.0 <2.7.2"
flutter:
  uses-material-design: true
